enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app


[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "both"
build-mode = "both"
included-patches = "'Permanent shuffle' 'Permanent repeat'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "both"
build-mode = "both"
included-patches = "'Enable slide to seek' 'Remove player controls background' 'Custom branding'"
